<a href="https://colab.research.google.com/github/sgpatel/MachineLearning/blob/master/MathematicsForML_TF_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathematics for machine learning


In [ ]:
import numpy as np
P=np.array([[1,2],[2,3],[3,4]])
#print(P)
print(P+P)
print(P*P)

[[2 4]
 [4 6]
 [6 8]]
[[ 1  4]
 [ 4  9]
 [ 9 16]]


In [ ]:
Q=np.array([[9,8],[8,7],[7,6]])

R=np.multiply(P,Q)
print(R)
S=np.add(R,P)
print(S)

[[ 9 16]
 [16 21]
 [21 24]]
[[10 18]
 [18 24]
 [24 28]]


**EugenValues and EigenVectors**

https://byjus.com/maths/eigenvector/

Eigenvector of a square matrix is defined as a non-vector in which when a given matrix is multiplied,  it is equal to a scalar multiple of that vector. Let us suppose that A is an n x n square matrix, and if v be a non-zero vector, then the product of matrix A, and vector v is defined as the product of a scalar quantity λ and the given vector, such that:

Av =λv

Where

v = Eigenvector and λ be the scalar quantity that is termed as eigenvalue associated with given matrix A

Eigenvector Equation
The equation corresponding to each eigenvalue of a matrix is given by:

AX = λ X

It is formally known as the eigenvector equation.

In place of λ, substitute each eigenvalue and get the eigenvector equation which enables us to solve for the eigenvector belonging to each eigenvalue.


In [5]:
import numpy as np
A = np.array([[2,-2,3],[1,1,1],[1,3,-1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [8]:
#calculate Eigen pairs
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[ 3.  1. -2.]
[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [9]:
import numpy as np
A = np.array([[2,0,0],[0,1,0],[0,0,-1]])
print(A)

[[ 2  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [13]:
#Eigen values of digonal matrix
values, vectors = np.linalg.eig(A)
print(values)

[ 2.  1. -1.]


In [12]:
print(vectors)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
