<a href="https://colab.research.google.com/github/sgpatel/MachineLearning/blob/master/TensorFlow_with_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathematics for machine learning


In [ ]:
import numpy as np
P=np.array([[1,2],[2,3],[3,4]])
#print(P)
print(P+P)
print(P*P)

[[2 4]
 [4 6]
 [6 8]]
[[ 1  4]
 [ 4  9]
 [ 9 16]]


In [ ]:
Q=np.array([[9,8],[8,7],[7,6]])

R=np.multiply(P,Q)
print(R)
S=np.add(R,P)
print(S)

[[ 9 16]
 [16 21]
 [21 24]]
[[10 18]
 [18 24]
 [24 28]]
